### ISSUE TITLE
Connection.swift:9:8: No such module 'CMySQL'

### ISSUE THREAD

**Issue by zzyyzz1992** [Zewo/MySQL#5]

**Comment by collinhundley** [comment]
Ditto. Should CMySQL be a dependency here?

**Comment by Danappelxx** [comment]
@collinhundley Yeah, MySQL hasn't been updated in a while (PostgreSQL has been getting a better treatment, though). If you hop in to the [Zewo Slack](http://slack.zewo.io) I can help you out one-on-one to work through that :)
